// Generated by CoffeeScript 1.4.0
(function() {
  var MongoClient, articleId, userId;

  MongoClient = require('mongodb').MongoClient;

  userId = 33;

  articleId = 393534;

  MongoClient.connect('mongodb://localhost:27017/gabby', function(err, db) {
    var article, articlesCollection, user, usersCollection;
    if (err) {
      return console.dir(err);
    }
    usersCollection = db.collection('users');
    user = usersCollection.findOne({
      _id: userId
    }, function(err, item) {});
    if (!user) {
      user = {
        _id: userId,
        location: -1
      };
      usersCollection.insert(user, function(err, item) {});
    }
    articlesCollection = db.collection('articles');
    article = articlesCollection.findOne({
      _id: articleId
    }, function(err, item) {});
    if (!article) {
      article = {
        _id: articleId,
        chats: []
      };
      articlesCollection.insert(article, function(err, item) {});
    }
  });

  return;

}).call(this);
