// Generated by CoffeeScript 1.4.0
(function() {
  var MongoClient, dbURL;

  MongoClient = require('mongodb').MongoClient;

  dbURL = 'mongodb://localhost:27017/gabby';

  exports.list = function(req, res) {
    var responseJSON;
    responseJSON = '';
    MongoClient.connect(dbURL, function(err, db) {
      var articlesCollection;
      if (err) {
        return console.dir(err);
      }
      articlesCollection = db.collection('articles');
      responseJSON = usersCollection.find().toArray(function(err, results) {
        res.send(results);
      });
    });
  };

  exports.listArticle = function(req, res) {
    var articleId, userId;
    articleId = parseInt(req.params.articleId);
    userId = parseInt(req.params.userId);
    return MongoClient.connect(dbURL, function(err, db) {
      var article, articlesCollection;
      if (err) {
        return console.dir(err);
      }
      articlesCollection = db.collection('articles');
      article = articlesCollection.findOne({
        _id: articleId
      }, function(err, item) {
        var newArticle, usersCollection;
        if (err) {
          return console.dir(err);
        }
        if (item) {
          usersCollection = db.collection('users');
          usersCollection.update({
            _id: userId
          }, {
            location: articleId
          }, function(err, item) {});
          res.send(item);
        } else {
          newArticle = {
            _id: articleId,
            chats: []
          };
          articlesCollection.insert(newArticle, function(err, item) {
            if (err) {
              return console.dir(err);
            }
            usersCollection = db.collection('users');
            usersCollection.update({
              _id: userId
            }, {
              location: articleId
            }, function(err, item) {});
            res.send(item);
          });
        }
      });
    });
  };

}).call(this);
