// Generated by CoffeeScript 1.4.0
(function() {
  var MongoClient, dbURL;

  MongoClient = require('mongodb').MongoClient;

  dbURL = 'mongodb://localhost:27017/gabby';

  exports.list = function(req, res) {
    var responseJSON;
    responseJSON = '';
    MongoClient.connect(dbURL, function(err, db) {
      var usersCollection;
      if (err) {
        return console.dir(err);
      }
      usersCollection = db.collection('users');
      responseJSON = usersCollection.find().toArray(function(err, results) {
        res.send(results);
      });
    });
  };

}).call(this);
